SUPPORT_EMAIL = "support@easypost.com"
TIMEOUT = 60

FEDEX_ACCOUNT_TYPE = "FedexAccount"
UPS_ACCOUNT_TYPE = "UpsAccount"

_CUSTOM_WORKFLOW_CARRIER_ACCOUNT_TYPES = [FEDEX_ACCOUNT_TYPE, UPS_ACCOUNT_TYPE]
